# https://circleci.com/docs/2.0/config-intro/

version: 2.1

orbs:
  node: circleci/node@5.0.3

# jobs:
#   app-build:
#     docker:
#       - image: cimg/node:16.18.0-browsers
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - run:
#           command: yarn lint
#           name: Run linters

workflows:
  run-npm-command:
    jobs:
      - node/run:
          yarn-run: build
# VS Code Extension Version: 1.0.2
