# https://circleci.com/docs/2.0/config-intro/

version: 2.1

jobs:
  app-build:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - run:
          name: 'Running linters'
          command: yarn lint

workflows:
  test-flow:
    jobs:
      - app-build
# VS Code Extension Version: 1.0.2
